### ISSUE TITLE
Create documentation for Image Tooltips

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#11]
Add a new item entry under **Image Tools** named **Image Tooltips**

 * XAML Image Tooltips (on hover and in IntelliSense) 
 * Android Resource.[Drawable|MipMap] image tooltips

**Comment by AlexHedley** [comment]
Is this up for grabs?

**Comment by matthewrdev** [comment]
I'll need to check with @ravero but I believe that this is.

**Comment by ravero** [comment]
Sure @AlexHedley, go ahead.
If you need any assistance get in touch.
Thanks for contributing!

**Comment by AlexHedley** [comment]
Great, thanks
I've started the PR #16, would love some feedback and happy to make any adjustments where necessary.

**Comment by matthewrdev** [comment]
Thanks for the contribution Alex. This is now live on our docs site. 🎉
