### ISSUE TITLE
Document color analysers

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#14]
Place under `Xamarin.Forms/Colors/Color Analysis.md`.

Please document the following analysers:

 * MalformedHexadecimalColorValue.cs
 * HexadecimalValueMatchesNamedColor.cs
 * ColorValueCloselyMatchesAvailableStaticResource.cs
 * ColorValueCanBeReplacedWithStaticResource.cs

**Comment by ravero** [comment]
@matthewrdev have published the docs to:
https://docs.mfractor.com/xamarin-forms/colors/color-analysis/

Please take a look and tell me if I've missed some part or detail.

**Comment by matthewrdev** [comment]
@ravero Looks good! That covers those analysers.
