### ISSUE TITLE
Create documentation for the View-ViewModel navigation feature suite.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#2]
Please see: https://docs.mfractor.com/xamarin-forms/working-with-viewmodels/view-viewmodel-navigation/

# Template

## Introduction 

What is a view? What is a view model? What is their relationship?

## Navigating to a View

Conditions for this shortcut to activate (either in a code behind or a view model).
Highlight shortcut is `Command+Shift+3`

## Navigating to a ViewModel

Conditions for this shortcut to activate (either in a view or a code behind).
Highlight shortcut is `Command+Shift+1`

## Navigating to a Code Behind

Conditions for this shortcut to activate (either in a view or a view model).
Highlight shortcut is `Command+Shift+2`

**Comment by matthewrdev** [comment]
@ravero Please move onto this after competing the Windows features.

**Comment by ravero** [comment]
Published.
