### ISSUE TITLE
Create documentation section under "Analysis" on how to disable code analysers

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#27]
We should inform the user how to disable analysers via:

 * The preferences panel.
 * Document level suppression statements (`<!-- [MFractor: Suppress(MF1001)]-->`)

**Comment by AlexHedley** [comment]
Added initial info on Disabling Analysers

**Comment by matthewrdev** [comment]
Thanks @AlexHedley. Did you want to raise a PR to merge this in?

**Comment by AlexHedley** [comment]
Should be able to finish this tomorrow then I will

**Comment by matthewrdev** [comment]
😚👌
