### ISSUE TITLE
Create a documentation named "General" that groups misc articles into a clean menu section

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#28]
The documentations left hand panel is getting a bit messy and its time to clean it up.

Please create a new section named "General" that groups the following articles:

 * Support
 * Licensing
 * Resharper compatibility
 * FAQ
 * Contributing

**Comment by AlexHedley** [comment]
@matthewrdev is this up for grabs?

**Comment by ravero** [comment]
Hi @AlexHedley,
Sure! We're open for contrib.
Thanks 🙂

**Comment by AlexHedley** [comment]
PR #29

**Comment by matthewrdev** [comment]
Thanks for the contribution Alex!
