### ISSUE TITLE
Create documentation for Data Binding IntelliSense

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#3]
Placeholder is here: https://docs.mfractor.com/xamarin-forms/working-with-viewmodels/data-binding-intellisense/

Please merge in this doc: https://docs.mfractor.com/xamarin-forms/working-with-viewmodels/generating-properties-and-commands/

# Template

## Introduction

What is data-binding intellisense? Why suggest properties from view models?

How does MFractor figure out a ViewModel for a view?

## How to Use Data-BInding Property IntelliSense

As a user, what do I have to do to activate 

## Generating Commands And Properties

How can I use the Generate a Propety and Generate a command completions to create property/command stubs on the View Model.

**Comment by matthewrdev** [comment]
@ravero Please move onto this after competing the Windows features.

**Comment by ravero** [comment]
Published [here](https://docs.mfractor.com/xamarin-forms/working-with-viewmodels/data-binding-intellisense/).
