### ISSUE TITLE
Create documentation for MFractors Xamarin.Forms color actions.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#31]
These should be placed under the category:

 * Xamarin.Forms -> Colors -> code-actions.md

This document should include the following refactorings:

 * Add transparency channel to color.
 * Convert named color to hex.
 * Edit color using color editor.

**Comment by ravero** [comment]
Published [here](https://docs.mfractor.com/xamarin-forms/colors/code-actions/).

**Comment by matthewrdev** [comment]
@ravero 🙏🙏
