### ISSUE TITLE
Create documentation for MFractors Thickness anlaysis features

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#32]
This should be place under

```
Xamarin.Forms -> Thickness -> analysis.md
```

The following analysers require documetnation:

 * InvalidThicknessAttributeValue
 * ThicknessCanBeConsolidated
 * ThicknessValueCanBeReplacedByStaticResource
 * ThicknessValueCanBeSimplified

**Comment by ravero** [comment]
[Published](https://docs.mfractor.com/xamarin-forms/analysis/thickness-analysis/).
Also added [Xamarin.Forms Code Analysis overview doc stub](https://docs.mfractor.com/xamarin-forms/analysis/overview/).

**Comment by matthewrdev** [comment]
Hi @ravero, I'm going to reopen this ticket as the invalid thickness value, thickness can be replaced by static resource and thickness can be simplieifed analysers are not included in the linked documentation.

**Comment by ravero** [comment]
Actually the _thickness can be replaced by static resource_ is already exposed on the section [_Applying Existing Static Resources_](https://docs.mfractor.com/xamarin-forms/analysis/thickness-analysis/#applying-existing-static-resources). I'll be adding the other 2.

**Comment by ravero** [comment]
@matthewrdev I've updated the docs, please check if it as expected:
- https://docs.mfractor.com/xamarin-forms/thicknesses/analysis/
- https://docs.mfractor.com/xamarin-forms/thicknesses/consolidation/
- https://docs.mfractor.com/xamarin-forms/thicknesses/invalid-thickness/
