### ISSUE TITLE
Create documentation for the "Copy Android Package ID To Clipboard" solution pad action feature.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#42]
To access, right click on an Android in the project in the solution explorer and this feature should be under tools.

**Comment by ravero** [comment]
Is it ported to Windows? I couldn't find the command.

**Comment by ravero** [comment]
Published at [here](https://docs.mfractor.com/android/tools/copy-package-id/).

**Comment by matthewrdev** [comment]
@ravero No, this command is not yet ported to Windows. Please feel free to integrate it via a command binding if you'd like :)

**Comment by ravero** [comment]
Updated docs:
- Added "Professional" note
- Added instructions for invoking on Windows
- Added instructions for calling resync
