### ISSUE TITLE
Create documentation for the Edit Android Manifest solution pad command

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#44]

**Comment by matthewrdev** [comment]
To access, right click on an Android project and choose Open Android Manifest.

**Comment by AlexHedley** [comment]
@matthewrdev should this be next to "Copy Package Id"?

This wasn't showing at first so I followed the tip on [Copy Package Id](https://docs.mfractor.com/android/tools/copy-package-id/) to [resync](https://docs.mfractor.com/utilities/resync-mfractor-resources/), that option then appeared but not "Edit Android Manifest.

Windows  
![image](https://user-images.githubusercontent.com/1573469/86510385-12479e80-bde7-11ea-83fc-2dccfcf7e707.png)

**Comment by matthewrdev** [comment]
@AlexHedley I don't think this command has been connected in Visual Studio Windows yet. Can you please file a bug and complete the docs for just the mac product?
