### ISSUE TITLE
Create documentation for the "Copy iOS Bundle ID To Clipboard" solution pad action feature.

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor.github.io#45]
To access, right click on an iOS in the project in the solution explorer and this feature should be under tools.

**Comment by ravero** [comment]
Published [here](https://docs.mfractor.com/ios/tools/copy-bundle-id/).

**Comment by AlexHedley** [comment]
Should this be updated to the iOS specific ID?

> The project Package ID (as defined on the AndroidManifest.xml file) will be copied to your clipboard.

Is this in the `info.plist` or `iTunesMetadata.plist`?

**Comment by matthewrdev** [comment]
@AlexHedley Good catch, I'll update this to say `info.plist`.

**Comment by ravero** [comment]
My bad, sorry! 🤷🏼‍♂️
