### ISSUE TITLE
Create documentation for the Generate Custom Renderers feature.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#6]
Placeholder: https://docs.mfractor.com/xamarin-forms/custom-renderers/generate-custom-renderers/

To trigger this refactoring, press Alt+Return on the name of the control in its C# file and choose `Generate custom renderers for ..."

![image](https://user-images.githubusercontent.com/3260473/71759197-85865b80-2efd-11ea-9b14-4d8a3826e05c.png)

This feature is implemented by `GenerateCustomRenderers.cs` in the MFractor.Forms project.

**Comment by ravero** [comment]
Done at https://docs.mfractor.com/xamarin-forms/custom-renderers/generate-custom-renderers/
