### ISSUE TITLE
Create documentation for the Find Custom Renderers feature

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor.github.io#7]
Placeholder: https://docs.mfractor.com/xamarin-forms/custom-renderers/find-custom-renderers/

To run this search, right click on the name of the control in its C# file and choose `Find Custom Renderers"

This feature is implemented by `FindCustomRenderers.cs` in the MFractor.Forms project.

**Comment by ravero** [comment]
Published.
